name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.207.6.216 << 'EOF'
            source ~/.bashrc
            cd /home/ubuntu/Projetos/backend
            git pull origin main
            npm install --production
            npm run build
            cp /home/ubuntu/Projetos/shared/conf/.env /home/ubuntu/Projetos/backend/build/
            pm2 restart meu-ingresso-api
          EOF
