name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Run Deploy Script
        run: |
          ssh -t -o StrictHostKeyChecking=no ubuntu@18.207.6.216 << 'EOF'
            export NVM_DIR="/home/ubuntu/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH="$PATH:$(yarn global bin)"
            cd /home/ubuntu/Projetos/backend
            git pull
            ./start.sh
          EOF
