name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Run Deploy Script
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.207.6.216 << 'EOF'
            cd /home/ubuntu/Projetos/backend
            ./start.sh
          EOF
