name: Deploy Application

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Run Deploy Script
        run: |
          BRANCH=${{ github.ref_name }}
          echo "VARIAVEL BRANCH: $BRANCH"
          if [ "$BRANCH" == "main" ]; then
            ENVIRONMENT="prod"
            GIT_BRANCH="main"
          elif [ "$BRANCH" == "staging" ]; then
            ENVIRONMENT="staging"
            GIT_BRANCH="staging"
          else
            echo "Branch $BRANCH não configurada para deploy."
            exit 1
          fi

          ssh -o StrictHostKeyChecking=no ubuntu@18.207.6.216 << EOF
            export NVM_DIR="/home/ubuntu/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
            export PATH="\$PATH:$(yarn global bin)"
            export ENVIRONMENT=$ENVIRONMENT
            cd /home/ubuntu/Projetos/backend-\$ENVIRONMENT
            git fetch --all
            git reset --hard origin/main
            ENVIRONMENT=\$ENVIRONMENT ./start.sh
          EOF
